FROM harbor.saas.bzlrobot-ift.com/cheetah/cheetah_base:v0.2

MAINTAINER wuchunming02@countrygarden.com.cn

ENV DEBIAN_FRONTEND noninteractive

COPY build-cheetah-16.04.sh /usr/local/bin/build-cheetah.sh

RUN mkdir /cheetah && chmod a+x /usr/local/bin/build-cheetah.sh

ENTRYPOINT ["bash", "/usr/local/bin/build-cheetah.sh"]

